#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'mysql'
cookbook 'apache2'
cookbook 'php'
cookbook 'build-essential'
cookbook 'users'
cookbook 'sudo'
cookbook 'vim'
